### PR TITLE
Load the requirements.txt in setup.py

### PR DESCRIPTION
**Pull request by Tiboris**
Load the content of requirements.txt file
instead of having static list in setup.py

Resolves https://github.com/pvoborni/mrack/issues/15 

Signed-off-by: Tibor Dudlák <tdudlak@redhat.com>

### CODE REVIEW

**Comment by netoarmando** [comment]
Should we also include the packages from: 
https://github.com/pvoborni/mrack/blob/8ec7bf98391adb4bc02de381268577f857bbdd0a/azure-pipelines.yml#L26

Maybe as `test` or `dev` requirements.

**Comment by pvoborni** [comment]
> Should we also include the packages from:
> 
> https://github.com/pvoborni/mrack/blob/8ec7bf98391adb4bc02de381268577f857bbdd0a/azure-pipelines.yml#L26
> 
> Maybe as `test` or `dev` requirements.

We should probably add them to test-requirements.txt But my "Python good practices knowledge" is limited here.

**Comment by Tiboris** [comment]
> We should probably add them to test-requirements.txt But my "Python good practices knowledge" is limited here.

Yes I do agree. We should have all requirement to test locally in `test-requirements.txt` and if something more is needed in azure pipeline we should add it in azure's yaml.

**Comment by netoarmando** [comment]
@Tiboris +1 to your proposal, I think you should include that to this PR.

**Pull request merged**
