### PR TITLE
Enable isort linting

### PR DESCRIPTION
**Pull request by netoarmando**
Helper tool to sort the imports for us.

Signed-off-by: Armando Neto <abiagion@redhat.com>

### CODE REVIEW

**Comment by pvoborni** [comment]
Could be good. I usually run `make format` for black formatting before commit. Should we add it there as well to sort the imports before black kicks in? So that later the the check will pass?

**Comment by netoarmando** [comment]
> Could be good. I usually run `make format` for black formatting before commit. Should we add it there as well to sort the imports before black kicks in? So that later the the check will pass?

I've included that as well. 
Leaving as WIP until we merge https://github.com/pvoborni/mrack/pull/14 so we can run this to fix the imports.

**Comment by pvoborni** [comment]
Did a quick read through the changes. Looks good to me. Did not test, I'll leave it on Tibor.

**Comment by Tiboris** [comment]
Thanks for the patch @netoarmando let us merge this!

**Pull request merged**
